### PR TITLE
Mobile Navbar -- Pair-Programming

### PR DESCRIPTION
**Pull request by LuisSalas94**
**Hello Microverse team**
In this branch We:
- Modified index.html
- Added icon to the movie version
- Added navbar styles
- Added JavaScript section
- Added changes to index.html
- Fixed linters issues

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
## Hi @LuisSalas94  

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Nice job :clap: using `Javascript` for implementing this mobile menu feature, Hovever one of the requirements says that you should set up both JavaScript and HTML&CSS linters in the project repository.  Kindly follow [these](https://github.com/microverseinc/linters-config/tree/master/html-css-js) intructions for the both linters configuration. Check here 👇  down 

Your configuration | the better configuration with Js
------|-----
image | image



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by LuisSalas94** [comment]
Hi @andersonlebon 
Thanks for the feedback. I did add JavaScript linters config and followed all steps.  
It passed all the tests. What should  I do now?

**Comment by andersonlebon** [comment]
Hello @LuisSalas94 kindly you need to update also your `linters.yml` file. currently, you just have 3 checks but after updating your `linters.yml` file you will have 4checks.

image

**Comment by LuisSalas94** [comment]
**Hi @andersonlebon** 
I really appreciate your help. I was able to solve it. 
Thanks

**Comment by andersonlebon** [comment]
It's my pleasure sir!

**Review by DammyShittu — APPROVED** [review]
Hi @LuisSalas94 , 

# APPROVED 🟢 

_Outstanding implementation of the features in this milestone and changes suggested by the previous reviewer.✔️ _

Your portfolio looks amazing 🤸‍♂️ 

Kudos to you 💯 

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

## CONGRATULATIONS! 🎉 

# OPTIONAL SUGGESTIONS ♻️ 

- The button/link to close the mobile menu is not very visible. Let's fix that and complete the beautiful work that you have done. 😀 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by LuisSalas94** [comment]
**Hi @DammyShittu** 
I really appreciate your words. 
Thank you!!!

**Pull request merged**
